[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functions = "netlify/functions"
  port = 8888

[[redirects]]
  from = "/steaminfo/:appId"
  to = "/.netlify/functions/getSteamInfo?appId=:appId"
  status = 200
